// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: one.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Avatar:
	//	*Profile_ImageUrl
	//	*Profile_ImageData
	Avatar isProfile_Avatar `protobuf_oneof:"avatar"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_one_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_one_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_one_proto_rawDescGZIP(), []int{0}
}

func (m *Profile) GetAvatar() isProfile_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (x *Profile) GetImageUrl() string {
	if x, ok := x.GetAvatar().(*Profile_ImageUrl); ok {
		return x.ImageUrl
	}
	return ""
}

func (x *Profile) GetImageData() []byte {
	if x, ok := x.GetAvatar().(*Profile_ImageData); ok {
		return x.ImageData
	}
	return nil
}

type isProfile_Avatar interface {
	isProfile_Avatar()
}

type Profile_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type Profile_ImageData struct {
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*Profile_ImageUrl) isProfile_Avatar() {}

func (*Profile_ImageData) isProfile_Avatar() {}

var File_one_proto protoreflect.FileDescriptor

var file_one_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x1d, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1f,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x08, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2e, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x3b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_one_proto_rawDescOnce sync.Once
	file_one_proto_rawDescData = file_one_proto_rawDesc
)

func file_one_proto_rawDescGZIP() []byte {
	file_one_proto_rawDescOnce.Do(func() {
		file_one_proto_rawDescData = protoimpl.X.CompressGZIP(file_one_proto_rawDescData)
	})
	return file_one_proto_rawDescData
}

var file_one_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_one_proto_goTypes = []interface{}{
	(*Profile)(nil), // 0: account.Profile
}
var file_one_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_one_proto_init() }
func file_one_proto_init() {
	if File_one_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_one_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_one_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Profile_ImageUrl)(nil),
		(*Profile_ImageData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_one_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_one_proto_goTypes,
		DependencyIndexes: file_one_proto_depIdxs,
		MessageInfos:      file_one_proto_msgTypes,
	}.Build()
	File_one_proto = out.File
	file_one_proto_rawDesc = nil
	file_one_proto_goTypes = nil
	file_one_proto_depIdxs = nil
}
